apiVersion: v1
kind: Service
metadata:
  name: bot
  namespace: application
spec:
  type: LoadBalancer
  selector:
    app: bot
  ports:
    - name: bot
      port: 8080
      targetPort: 8080

    - name: management
      port: 8000
      targetPort: 8000
