apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: message-broker
spec:
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
