apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: message-broker
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - name: external
      port: 9094
      targetPort: 9094
