apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: db
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-data
              mountPath: /data
          command: ["redis-server"]
          args:
            - "--save"
            - "60"
            - "1"
            - "--loglevel"
            - "warning"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
