apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper
  namespace: application
spec:
  selector:
    matchLabels:
      app: scrapper
  template:
    metadata:
      labels:
        app: scrapper
    spec:
      containers:
        - name: scrapper
          image: stacenko63/scrapper
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - name: scrapper
              containerPort: 8081
            - name: management
              containerPort: 8001
          envFrom:
            - secretRef:
                name: scrapper-secrets
      imagePullSecrets:
        - name: dockerhub-secret
