apiVersion: v1
kind: Service
metadata:
  name: scrapper
  namespace: application
spec:
  type: LoadBalancer
  selector:
    app: scrapper
  ports:
    - name: scrapper
      port: 8081
      targetPort: 8081

    - name: management
      port: 8001
      targetPort: 8001
