name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: edu-self-hosted
    container:
      image: maven:3-eclipse-temurin-23
    timeout-minutes: 10
    name: Build
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: maven build
        run: mvn verify

      - name: Upload bot JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-jar
          path: bot/target/bot-1.0.jar
          retention-days: 7

      - name: Upload scrapper JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: scrapper-jar
          path: scrapper/target/scrapper-1.0.jar
          retention-days: 7

      - id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/report/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true

  linter:
    name: linter
    runs-on: edu-self-hosted
    container:
      image: maven:3-eclipse-temurin-23
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - run: mvn compile -am spotless:check modernizer:modernizer spotbugs:check pmd:check pmd:cpd-check

  docker-build:
    needs: [ build, linter ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      BOT_IMAGE_NAME: ghcr.io/stacenko63/bot
      SCRAPPER_IMAGE_NAME: ghcr.io/stacenko63/scrapper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Download bot JAR
        uses: actions/download-artifact@v4
        with:
          name: bot-jar
          path: target

      - name: Download scrapper JAR
        uses: actions/download-artifact@v4
        with:
          name: scrapper-jar
          path: target

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push bot image
        run: |
          docker build -t ${BOT_IMAGE_NAME} -f bot/bot.Dockerfile .
          docker push ${BOT_IMAGE_NAME}

      - name: Build and push scrapper image
        run: |
          docker build -t ${SCRAPPER_IMAGE_NAME} -f scrapper/scrapper.Dockerfile .
          docker push ${SCRAPPER_IMAGE_NAME}

